{{- if .Values.ingress.enabled  }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "onwards.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "onwards.labels" . | nindent 4 }}
    {{- with .Values.ingress.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  rules:
    {{- .Values.ingress.rules | toYaml | nindent 4 }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- toYaml .Values.ingress.tls | nindent 4 }}
  {{- end }}
---
{{- end }}