{{- if .Values.metrics.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "onwards.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "onwards.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "onwards.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s
{{- end }}