apiVersion: olm.operatorframework.io/v1
kind: ClusterExtension
metadata:
  name: model-orchestra-operator-0.1.1
spec:
  namespace: model-orchestra-operator-system
  serviceAccount:
    name: model-orchestra-operator
  source:
    sourceType: Catalog
    catalog:
      packageName: model-orchestra-operator
      channels: ["stable-v0"]
      version: "v0.1.1"