# This should not need to be installed as should be created with setup script. Just here for reference.
apiVersion: olm.operatorframework.io/v1
kind: ClusterCatalog
metadata:
  name: operatorhubio
spec:
  source:
    type: Image
    image:
      ref: docker.io/tytn/operator-catalog:0.0.5
      pollIntervalMinutes: 10