{
 "title": "LMCache Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Average time to first token (sec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "vllm:time_to_first_token_seconds_sum / vllm:time_to_first_token_seconds_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "LMCache retrieve speed (K Tokens / sec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(lmcache:retrieve_speed_sum[1m])) / sum(rate(lmcache:retrieve_speed_count[1m])) / 1e3",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache hit rate (%) in last 1 minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "rate(lmcache:num_hit_tokens_total[1m]) / (rate(lmcache:num_requested_tokens_total[1m]) + 1e-10) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Local CPU cache usage (GB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "lmcache:local_cache_usage / 1e9",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of requested tokens in total",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "lmcache:num_requested_tokens_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of hit tokens in total",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "lmcache:num_hit_tokens_total", "legendFormat": "__auto" }
   ]
  }
 ]
}