{
 "title": "RAG API Server",
 "description": "API metrics from the rag/helios server which is the main interface for the application",
 "tags": [ "RAG" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Query", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Requests per Second",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(handler, namespace) (rate(helios_http_requests_total{handler=~\".*chunks\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Percent of 2xx Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (handler, namespace) (\n    rate(helios_http_requests_total{status=~\"2..\", handler=~\".*chunks\"}[1m])\n/\n    rate(helios_http_requests_total{handler=~\".*chunks\"}[1m])\n)",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Percentage of 4xx Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (handler, namespace) (\n    rate(helios_http_requests_total{status=~\"4..\", handler=~\".*chunks\"}[1m])\n/\n    rate(helios_http_requests_total{handler=~\".*chunks\"}[1m])\n)",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Percentage of 5xx Errors",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (handler, namespace) (\n    rate(helios_http_requests_total{status=~\"5..\", handler=~\".*chunks\"}[1m])\n/\n    rate(helios_http_requests_total{handler=~\".*chunks\"}[1m])\n)",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "HTTP Duration Distribution ",
   "type": "bargauge",
   "description": "Duration distribution of http requests",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "helios_http_request_duration_seconds_bucket{handler=~\".*chunks\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "HTTP Average Duration",
   "type": "timeseries",
   "description": "Average duration of requests.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(helios_http_request_duration_seconds_bucket{handler=~\".*/chunks\"}[1m])) by (le))",
     "legendFormat": "95th Percentile"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(helios_http_request_duration_seconds_bucket{handler=~\".*/chunks\"}[1m])) by (le))",
     "legendFormat": "99th Percentile"
    },
    {
     "expr": "sum(rate(helios_http_request_duration_seconds_sum{handler=~\".*/chunks\"}[1m])) / sum(rate(helios_http_request_duration_seconds_count{handler=~\".*/chunks\"}[1m]))",
     "legendFormat": "Average"
    }
   ]
  },
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Requests per Second",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 11, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(handler, namespace) (rate(helios_http_requests_total{ handler!~\".*health|.*status\", handler=~\"/api/.*\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Percent of 2xx Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (handler, namespace) (\n    rate(helios_http_requests_total{status=~\"2..\", handler=~\"/api/.*\"}[1m])\n/\n    rate(helios_http_requests_total{handler=~\"/api/.*\"}[1m])\n)",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Percentage of 4xx Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (handler, namespace) (\n    rate(helios_http_requests_total{status=~\"4..\", handler=~\"/api/.*\"}[1m])\n/\n    rate(helios_http_requests_total{handler=~\"/api/.*\"}[1m])\n)",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Requests per Second (status)",
   "type": "timeseries",
   "description": "Total requests to our status/health/metrics endpoints",
   "gridPos": { "h": 11, "w": 11, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(handler, namespace) (rate(helios_http_requests_total{handler=~\".*metrics|.*health|/api/v1/status\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Percentage of 5xx Errors",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 13, "x": 11, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (handler, namespace) (\n    rate(helios_http_requests_total{status=~\"5..\", handler=~\"/api/.*\"}[1m])\n/\n    rate(helios_http_requests_total{handler=~\"/api/.*\"}[1m])\n)",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "HTTP Duration Distribution",
   "type": "bargauge",
   "description": "Duration distribution of http requests",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "helios_http_request_duration_highr_seconds_bucket",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "Average HTTP Duration",
   "type": "timeseries",
   "description": "Average duration of http requests. Careful this metric will be heavily influenced by the health and metric queries.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 54 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(helios_http_request_duration_highr_seconds_bucket[5m])) by (le))",
     "legendFormat": "95th Percentile"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(helios_http_request_duration_highr_seconds_bucket[5m])) by (le))",
     "legendFormat": "99th Percentile"
    },
    {
     "expr": "sum(rate(helios_http_request_duration_highr_seconds_sum[5m])) / sum(rate(helios_http_request_duration_highr_seconds_count[5m]))",
     "legendFormat": "Average"
    }
   ]
  },
  { "title": "Document Ingestion", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 } },
  {
   "title": "Submitted",
   "type": "timeseries",
   "description": "Number of documents submitted to the server",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(helios_documents_submitted_total[$__rate_interval])",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Accepted",
   "type": "timeseries",
   "description": "The ratio of documents accepted via the api handler for async processing.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(helios_documents_duplicate_total[$__rate_interval])",
     "legendFormat": "Duplicates"
    },
    {
     "expr": "increase(helios_documents_accepted_total[$__rate_interval])",
     "legendFormat": "Accepted"
    },
    {
     "expr": "increase(helios_documents_invalid_total[$__rate_interval])",
     "legendFormat": "Invalid"
    }
   ]
  },
  {
   "title": "Processing",
   "type": "timeseries",
   "description": "The tracking of async document processing.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(helios_documents_failed_total[$__rate_interval])",
     "legendFormat": "Failures"
    },
    {
     "expr": "increase(helios_documents_imported_total[$__rate_interval])",
     "legendFormat": "Success"
    }
   ]
  },
  {
   "title": "Average HTTP Duration",
   "type": "timeseries",
   "description": "Average duration of http requests",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 70 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(helios_documents_batch_processing_seconds_bucket[1m])) by (le))",
     "legendFormat": "95th Percentile"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(helios_documents_batch_processing_seconds_bucket[1m])) by (le))",
     "legendFormat": "99th Percentile"
    },
    {
     "expr": "sum(rate(helios_documents_batch_processing_seconds_sum[1m])) / sum(rate(helios_documents_batch_processing_seconds_count[1m]))",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "Duration Distribution",
   "type": "bargauge",
   "description": "Grouping of processing duration of document batches",
   "gridPos": { "h": 11, "w": 9, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "helios_documents_batch_processing_seconds_bucket",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Long Processing Documents",
   "type": "timeseries",
   "description": "Number of documents in a 1 minute time frame that are greater than a threshold",
   "gridPos": { "h": 11, "w": 15, "x": 9, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(helios_documents_batch_processing_seconds_count[1m]) - ignoring(le) increase(helios_documents_batch_processing_seconds_bucket{le=\"600.0\"}[1m])",
     "legendFormat": "duration > 600"
    },
    {
     "expr": "increase(helios_documents_batch_processing_seconds_count[1m]) - ignoring(le) increase(helios_documents_batch_processing_seconds_bucket{le=\"300.0\"}[1m])",
     "legendFormat": "duration > 300"
    },
    {
     "expr": "increase(helios_documents_batch_processing_seconds_count[1m]) - ignoring(le) increase(helios_documents_batch_processing_seconds_bucket{le=\"60.0\"}[1m])",
     "legendFormat": "duration > 60"
    }
   ]
  }
 ]
}