# These resources constitute the fully configured set of manifests
# used to generate the 'manifests/' directory in a bundle.
resources:
- bases/model-orchestra-operator.clusterserviceversion.yaml
- ../default
