{{- if .Values.rproxy.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "takeoff-console.fullname" . }}-rproxy
  labels:
    {{- include "takeoff-console.labels" . | nindent 4 }}
    app.kubernetes.io/component: rproxy
spec:
  replicas: {{ .Values.rproxy.replicaCount }}
  selector:
    matchLabels:
      {{- include "takeoff-console.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: rproxy
  template:
    metadata:
      {{- with .Values.rproxy.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app.kubernetes.io/component: rproxy
        {{- include "takeoff-console.selectorLabels" . | nindent 8 }}
        {{- with .Values.rproxy.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "takeoff-console.serviceAccountName" . }}
      {{- with .Values.rproxy.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.rproxy.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.rproxy.image.repository }}:{{ .Values.rproxy.image.tag }}"
          imagePullPolicy: {{ .Values.rproxy.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
          env:
            - name: FRONTEND_SERVICE
              value: {{ include "takeoff-console.fullname" . }}-frontend
            - name: FRONTEND_PORT
              value: "{{ .Values.frontend.service.port }}"
            - name: BACKEND_SERVICE
              value: {{ include "takeoff-console.fullname" . }}-backend
            - name: BACKEND_PORT
              value: "{{ .Values.backend.service.port }}"
            - name: CONTROLLER_SERVICE
              value: {{ include "takeoff-console.takeoffCrName" . }}-controller
            - name: CONTROLLER_PORT
              value: "80"
          {{- with .Values.rproxy.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.rproxy.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.rproxy.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.rproxy.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "takeoff-console.fullname" . }}-rproxy
  labels:
    {{- include "takeoff-console.labels" . | nindent 4 }}
    app.kubernetes.io/component: rproxy
spec:
  type: {{ .Values.rproxy.service.type }}
  ports:
    - port: {{ .Values.rproxy.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/component: rproxy
    {{- include "takeoff-console.selectorLabels" . | nindent 4 }}
{{- end }}