apiVersion: v1
kind: Service
metadata:
  name: {{ include "takeoff-console.fullname" . }}-frontend
  labels:
    app.kubernetes.io/component: backend
    {{- include "takeoff-console.labels" . | nindent 4 }}
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/component: backend
    {{- include "takeoff-console.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "takeoff-console.fullname" . }}-backend
  labels:
    {{- include "takeoff-console.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/component: frontend
    {{- include "takeoff-console.selectorLabels" . | nindent 4 }}
