{
 "title": "Takeoff Stack Dash",
 "tags": [ "takeoff" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "INSTANCE",
    "label": "Instance",
    "query": {
     "query": "label_values(sampling_batch_size,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Proportion of 2xx responses",
   "type": "status-history",
   "description": "Rolling average over last minute.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "changes(http_requests_total{instance=\"$INSTANCE\", status=\"200\", path=~\"/embed|/generate|/generate_stream|/partition_document|/reader_groups|/status|/tokenize/:reader_id\"}[1m]) / changes(http_requests_total{instance=\"$INSTANCE\", path=~\"/embed|/generate|/generate_stream|/partition_document|/reader_groups|/status|/tokenize/:reader_id\"}[1m])",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Tokens/S and TTFT",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by(method) (rate(generate_sequence_lengths_sum{instance=\"$INSTANCE\"}[$__rate_interval])) / sum by(method) (rate(generate_sequence_lengths_count{instance=\"$INSTANCE\"}[$__rate_interval]))",
     "legendFormat": " {{path}} (Tok/s ovr RI)"
    },
    {
     "expr": "sum by(method) (rate(generate_sequence_lengths_sum{instance=\"$INSTANCE\"}[5m])) / sum by(method) (rate(generate_sequence_lengths_count{instance=\"$INSTANCE\"}[5m]))",
     "legendFormat": " {{path}} (Tok/s ovr 5min)"
    },
    {
     "expr": "sum by(method) (rate(time_to_first_token_sum{instance=\"$INSTANCE\"}[$__rate_interval])) / sum by(method) (rate(time_to_first_token_count{instance=\"$INSTANCE\"}[$__rate_interval]))",
     "legendFormat": "TTFT (s avg over RI) {{path}}"
    }
   ]
  },
  {
   "title": "Completed sequence lengths",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(quantile) (drain_sequence_lengths{instance=\"$INSTANCE\"})",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "Incoming sequence lengths",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(quantile) (fill_sequence_lengths{instance=\"$INSTANCE\"})",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "Tokens generated in last minute",
   "type": "stat",
   "gridPos": { "h": 9, "w": 3, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(method) (floor(increase(generate_sequence_lengths_sum{instance=\"$INSTANCE\"}[1m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "User supplied batch size",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(quantile) (user_batch_size{instance=\"$INSTANCE\"})",
     "legendFormat": "Quantile: {{quantile}}"
    }
   ]
  },
  {
   "title": "DPP Error Count / Hr",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(document_processing_errors_count{instance=\"$INSTANCE\"}[1h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DPP Queue Size & Active Workers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 4, "y": 17 },
   "targets": [
    { "expr": "document_processing_queue_size", "legendFormat": "__auto" },
    {
     "expr": "document_processing_active_workers",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}