{
 "title": "Takeoff Reader Dashboard (Generate)",
 "tags": [ "takeoff" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "CONSUMER_GROUP",
    "label": "Consumer Group",
    "query": {
     "query": "label_values(user_batch_size_count,consumer_group)"
    }
   },
   {
    "name": "INSTANCE",
    "label": "Instance",
    "query": {
     "query": "label_values(sampling_batch_size,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Proportion of 2xx responses",
   "type": "status-history",
   "description": "Rolling average over last minute.",
   "gridPos": { "h": 8, "w": 12, "x": 5, "y": 0 },
   "targets": [
    {
     "expr": "changes(http_requests_total{instance=\"$INSTANCE\", status=\"200\", path=~\"/embed|/generate|/generate_stream|/partition_document|/reader_groups|/status|/tokenize/:reader_id\"}[1m]) / changes(http_requests_total{instance=\"$INSTANCE\", path=~\"/embed|/generate|/generate_stream|/partition_document|/reader_groups|/status|/tokenize/:reader_id\"}[1m])",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Generation request duration / S",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expression": "$B / $A", "type": "math" }
   ]
  },
  {
   "title": "Tokens/S and TTFT",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by(method) (rate(generate_sequence_lengths_sum{consumer_group=\"$CONSUMER_GROUP\", instance=\"$INSTANCE\"}[$__rate_interval])) / sum by(method) (rate(generate_sequence_lengths_count{consumer_group=\"$CONSUMER_GROUP\", instance=\"$INSTANCE\"}[$__rate_interval]))",
     "legendFormat": " {{path}} (Tok/s ovr RI)"
    },
    {
     "expr": "sum by(method) (rate(generate_sequence_lengths_sum{consumer_group=\"$CONSUMER_GROUP\", instance=\"$INSTANCE\"}[5m])) / sum by(method) (rate(generate_sequence_lengths_count{consumer_group=\"$CONSUMER_GROUP\", instance=\"$INSTANCE\"}[5m]))",
     "legendFormat": " {{path}} (Tok/s ovr 5min)"
    },
    {
     "expr": "sum by(method) (rate(time_to_first_token_sum{consumer_group=\"$CONSUMER_GROUP\", instance=\"$INSTANCE\"}[$__rate_interval])) / sum by(method) (rate(time_to_first_token_count{consumer_group=\"$CONSUMER_GROUP\", instance=\"$INSTANCE\"}[$__rate_interval]))",
     "legendFormat": "TTFT (s avg over RI) {{path}}"
    }
   ]
  },
  {
   "title": "Completed sequence lengths",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(quantile) (drain_sequence_lengths{consumer_group=\"$CONSUMER_GROUP\", instance=\"$INSTANCE\"})",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "Incoming sequence lengths",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(quantile) (fill_sequence_lengths{consumer_group=\"$CONSUMER_GROUP\", instance=\"$INSTANCE\"})",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "Tokens generated in last minute",
   "type": "stat",
   "gridPos": { "h": 9, "w": 3, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(method) (floor(increase(generate_sequence_lengths_sum{instance=\"$INSTANCE\"}[1m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "User supplied batch size",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(quantile) (user_batch_size{consumer_group=\"$CONSUMER_GROUP\", instance=\"$INSTANCE\"})",
     "legendFormat": "Quantile: {{quantile}}"
    }
   ]
  },
  { "title": "State machine", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Stage timing",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "rate(state_machine_loop_time_Drain_sum{instance=\"$INSTANCE\"}[$__rate_interval])",
     "legendFormat": "drain"
    },
    {
     "expr": "rate(state_machine_loop_time_Generating_tokens_sum{instance=\"$INSTANCE\"}[$__rate_interval])",
     "legendFormat": "generation"
    },
    {
     "expr": "rate(state_machine_loop_time_Refill_sum[$__rate_interval])",
     "legendFormat": "refill"
    },
    {
     "expr": "rate(state_machine_loop_time_Waiting_for_input_sum{instance=\"$INSTANCE\"}[$__rate_interval])",
     "legendFormat": "prefill"
    }
   ]
  },
  {
   "title": "Stage counts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "rate(drain_count[$__rate_interval])",
     "legendFormat": "drain count"
    },
    {
     "expr": "rate(generate_count[$__rate_interval])",
     "legendFormat": "generate count"
    },
    {
     "expr": "rate(refill_count[$__rate_interval])",
     "legendFormat": "refill count"
    },
    {
     "expr": "rate(prefill_count[$__rate_interval])",
     "legendFormat": "prefill count"
    }
   ]
  },
  {
   "title": "SSD performance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    { "expr": "speculative_tokens_proposed", "legendFormat": "SSD tokens proposed" },
    {
     "expr": "speculative_tokens_accepted_fraction * speculative_tokens_proposed",
     "legendFormat": "SSD tokens accepted"
    }
   ]
  },
  {
   "title": "State machine batch size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "generate_batch_size{instance=\"$INSTANCE\"}",
     "legendFormat": "Generation batch size"
    }
   ]
  }
 ]
}