# permissions for end users to edit takeoffs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: takeoff-operator
    app.kubernetes.io/managed-by: kustomize
  name: takeoff-editor-role
rules:
- apiGroups:
  - charts.titanml.co
  resources:
  - takeoffs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - charts.titanml.co
  resources:
  - takeoffs/status
  verbs:
  - get
