# permissions for end users to edit inferencestacks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: inference-stack-operator
    app.kubernetes.io/managed-by: kustomize
  name: inference-stack-editor-role
rules:
- apiGroups:
  - models.takeoff.co
  resources:
  - inferencestacks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - models.takeoff.co
  resources:
  - inferencestacks/status
  verbs:
  - get
