# permissions for end users to view inferencestacks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: inference-stack-operator
    app.kubernetes.io/managed-by: kustomize
  name: inference-stack-viewer-role
rules:
- apiGroups:
  - doublewordai.co
  resources:
  - inferencestacks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - doublewordai.co
  resources:
  - inferencestacks/status
  verbs:
  - get
