apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: inference-stack-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - kind: InferenceStack
      name: inferencestacks.takeoff.com
      version: v1alpha1
  description: Operator for controlling model orchestra objects.
  displayName: inference-stack-operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - app
  - modelorchestra
  links:
  - name: Model Orchestra Operator
    url: https://inference-stack-operator.domain
  maturity: alpha
  provider:
    name: DoubleWord
  version: 0.0.0
