{{- if .Values.role.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "console.fullname" . }}-role
rules:
- apiGroups: ["charts.takeoff.co"]
  resources: ["inferencestacks"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
{{- end }}