{{- if .Values.cluster.leader }}
{{ if .Values.skipAuth }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "console.fullname" . }}-{{.Values.secretName}}
type: Opaque
stringData:
  dbUser: "postgres"
  dbPassword: "postgres"
  defaultAdmin: "admin@example.com"
  fqdn: "localhost"
  provider: "azure"
  clientId: "none"
  clientSecret: "none"
  authUrl: "none"
  tokenUrl: "none"
{{ end }}
{{- end }}
