{{- if .Values.cluster.leader }}
{{ if .Values.secret.generate }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "console.fullname" . }}-{{.Values.secret.name}}
type: Opaque
stringData:
  dbUser: "postgres"
  dbPassword: "postgres"
  publicAccess: "true"
  fqdn: "localhost"
  provider: "azure"
  clientId: "none"
  clientSecret: "none"
  authUrl: "none"
  tokenUrl: "none"
  tlsCertificatePem: ""
  tlsPrivateKeyPem: ""
{{ end }}
{{- end }}
