apiVersion: v1
kind: Service
metadata:
  name: {{ include "console.fullname" . }}-frontend
  labels:
    app.kubernetes.io/component: frontend
    {{- include "console.labels" . | nindent 4 }}
  {{- with .Values.frontend.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/component: frontend
    {{- include "console.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "console.fullname" . }}-backend
  labels:
    app.kubernetes.io/component: backend
    {{- include "console.labels" . | nindent 4 }}
  {{- with .Values.backend.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/component: backend
    {{- include "console.selectorLabels" . | nindent 4 }}
---
{{- if .Values.rproxy.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "console.fullname" . }}-rproxy
  labels:
    {{- include "console.labels" . | nindent 4 }}
    app.kubernetes.io/component: rproxy
spec:
  type: {{ .Values.rproxy.service.type }}
  {{- with .Values.rproxy.service.ports }}
  ports:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    app.kubernetes.io/component: rproxy
    {{- include "console.selectorLabels" . | nindent 4 }}
{{- end }}
