{{- if .Values.cluster.leader }}

apiVersion: v1
kind: Service
metadata:
  name: {{ include "console.fullname" . }}-frontend
  labels:
    app.kubernetes.io/component: frontend
    {{- include "console.labels" . | nindent 4 }}
  {{- with .Values.frontend.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/component: frontend
    {{- include "console.selectorLabels" . | nindent 4 }}
---
{{- if .Values.cluster.leader }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "console.fullname" . }}-backend
  labels:
    app.kubernetes.io/component: backend
    {{- include "console.labels" . | nindent 4 }}
  {{- with .Values.backend.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/component: backend
    {{- include "console.selectorLabels" . | nindent 4 }}
{{- end }}
---
{{- if .Values.reverseproxy.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "console.fullname" . }}-reverseproxy
  labels:
    {{- include "console.labels" . | nindent 4 }}
    app.kubernetes.io/component: reverseproxy
spec:
  type: ClusterIP
  {{- with .Values.reverseproxy.service.ports }}
  ports:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    app.kubernetes.io/component: reverseproxy
    {{- include "console.selectorLabels" . | nindent 4 }}
{{- end }}
---
{{- if .Values.debug.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "console.fullname" . }}-debug
  labels:
    {{- include "console.labels" . | nindent 4 }}
    app.kubernetes.io/component: debug
spec:
  type: ClusterIP
  {{- with .Values.debug.service.ports }}
  ports:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    app.kubernetes.io/component: debug
    {{- include "console.selectorLabels" . | nindent 4 }}
{{- end }}
---
{{- if .Values.authentication.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "console.fullname" . }}-authentication
  labels:
    {{- include "console.labels" . | nindent 4 }}
    app.kubernetes.io/component: authentication
  {{- with .Values.authentication.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.authentication.service.type }}
  {{- with .Values.authentication.service.ports }}
  ports:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    app.kubernetes.io/component: authentication
    {{- include "console.selectorLabels" . | nindent 4 }}
{{- end }}
---
{{- if .Values.apikeys.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "console.fullname" . }}-apikeys
  labels:
    {{- include "console.labels" . | nindent 4 }}
    app.kubernetes.io/component: apikeys
spec:
  type: ClusterIP
  {{- with .Values.apikeys.service.ports }}
  ports:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    app.kubernetes.io/component: apikeys
    {{- include "console.selectorLabels" . | nindent 4 }}
{{- end }}

{{- end}} # if .Values.cluster.leader }}
