applications:
  generate:
    gpusPerReplica: 1
    replicas: 1
    cacheStorageClass: hostpath
    cacheSize: 100Gi
    minReplicas: 1
    maxReplicas: 3
    scaleToZero: true
    cpuLimit: 1
    memoryLimit: 10Gi
    ephemeralMemoryLimit: 8Gi
    gpuType: nvidia-l4
    enableLivenessProbe: true
    enableStartupProbe: true

    env:

    readerConfig:
      device: cuda
      model_name: TitanML/dummy_model
      consumer_group: generate
      log_level: debug

  document-processing:
    # omitting gpusPerReplica = gpusPerReplica: 0 = use cpu only
    replicas: 1
    cacheStorageClass: hostpath
    cacheSize: 100Gi
    minReplicas: 1
    maxReplicas: 3
    scaleToZero: true
    cpuLimit: 16
    memory_limit: 40Gi
    ephemeralMemoryLimit: 10Gi
    enableLivenessProbe: true
    enableStartupProbe: true
    livenessInitialDelaySeconds: 180

    env:

    readerConfig:
      device: cpu
      model_name: TitanML/dummy_model
      consumer_group: document_processing
      log_level: debug
      enable_document_processing: true


  embed:
    # omitting gpusPerReplica = gpusPerReplica: 0 = use cpu only
    replicas: 1
    cacheStorageClass: hostpath
    cacheSize: 100Gi
    minReplicas: 1
    maxReplicas: 3
    scaleToZero: true
    cpuLimit: 1
    memoryLimit: 16Gi
    ephemeralMemoryLimit: 8Gi
    enableLivenessProbe: true
    enableStartupProbe: true
    env:

    readerConfig:
      device: cpu
      model_name: TitanML/jina-v2-code-embed
      consumer_group: embed
      log_level: debug
