takeoffVersion: 0.22.0-rc15
zeusBackendVersion: latest
zeusFrontendVersion: latest

deploymentPrefix: ""

useAWSLoadBalancer: false #aws
useGKENodeSelector: false #gcp

zeus:
  enabled: true

controller:
  enabled: true
  replicas: 1
  cpuLimit: 1
  memoryLimit: 5Gi
  reservedConsumers: generate,embed
  enableLivenessProbe: true
  enableStartupProbe: true

  env:
    TAKEOFF_EXTRA_ENV_VAR_EXAMPLE: hello
