{{- if .Values.clusterExtension.enabled }}
{{- range $clusterExtension := .Values.clusterExtension.versions }}
apiVersion: olm.operatorframework.io/v1
kind: ClusterExtension
metadata:
  name: {{ $clusterExtension.name }}
  labels:
    {{- include "catalog.labels" $ | nindent 4 }}
  {{- with $clusterExtension.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  serviceAccount:
    name: {{ include "catalog.serviceAccountName" $ }}
  {{- toYaml $clusterExtension.spec | nindent 2 }}
---
{{- end }}
{{- end }}