{{- if .Values.customResourceDefinition.enabled }}
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: inferencestacks.doublewordai.co
spec:
  group: doublewordai.co
  names:
    kind: InferenceStack
    listKind: InferenceStackList
    plural: inferencestacks
    singular: inferencestack
  scope: Namespaced
  versions:
    {{- toYaml .Values.customResourceDefinition.versions | nindent 4 }}
{{- end }}
