{{- range $appName, $baseValues := .Values.applications }}
  {{/* First, deep copy the application template */}}
  {{- $mergedValues := deepCopy $.Values.applicationTemplate }}
  
  {{/* Special handling for modelsVolume */}}
  {{- $appModelsVolume := dict }}
  {{- if hasKey $baseValues "modelsVolume" }}
    {{- $appModelsVolume = deepCopy $baseValues.modelsVolume }}
    {{- $baseValues = omit $baseValues "modelsVolume" }}
  {{- end }}
  
  {{/* Merge application values into template */}}
  {{- $mergedValues = mustMergeOverwrite $mergedValues $baseValues }}
  
  {{/* Handle modelsVolume - use application specific if provided, fall back to template, or use default if neither specified */}}
  {{- if not (empty $appModelsVolume) }}
    {{/* If app-specific modelsVolume was provided, use it */}}
    {{- $_ := set $mergedValues "modelsVolume" $appModelsVolume }}
  {{- else }}
    {{- if or (not (hasKey $mergedValues "modelsVolume")) (empty $mergedValues.modelsVolume) }}
      {{/* If no modelsVolume was specified in either place, use the default */}}
      {{- $defaultModelsVolume := dict "name" "models" "emptyDir" (dict "medium" "Memory") }}
      {{- $_ := set $mergedValues "modelsVolume" $defaultModelsVolume }}
    {{- end }}
  {{- end }}

  {{/* Set the required env vars needed for the reader container */}}
  {{- $readerEnv := list }}
  {{- $readerEnv = append $readerEnv (dict "name" "TAKEOFF_ADD_READER_ID_SUFFIX" "value" "true") }}
  {{- $readerEnv = append $readerEnv (dict "name" "TAKEOFF_HEADLESS" "value" "false") }}
  {{- $readerEnv = append $readerEnv (dict "name" "POD_NAME" "valueFrom" (dict "fieldRef" (dict "fieldPath" "metadata.name"))) }}

  {{/* Set the required env vars needed for the manager container */}}
  {{- $managerEnv := list }}
  {{- $managerEnv = append $managerEnv (dict "name" "TAKEOFF_ADD_READER_ID_SUFFIX" "value" "true") }}
  {{- $managerEnv = append $managerEnv (dict "name" "TAKEOFF_HEADLESS" "value" "true") }}
  {{- $managerEnv = append $managerEnv (dict "name" "TAKEOFF_READER_ENGINE" "value" "sglang") }}
  {{- $managerEnv = append $managerEnv (dict "name" "POD_NAME" "valueFrom" (dict "fieldRef" (dict "fieldPath" "metadata.name"))) }}

  {{/* Process template env */}}
  {{- $templateEnv := list }}
  {{- $templateEnv = concat $templateEnv $.Values.applicationTemplate.env }}

  {{/* Process app-specific env */}}
  {{- $appEnv := list }}
  {{- if hasKey $baseValues "env" }}
    {{- $appEnv = $baseValues.env }}
  {{- end }}

  {{/* Create combined env list with overrides for reader */}}
  {{- $allNames := dict }}
  {{- $readerApplicationEnv := list }}
  
  {{/* First add app-specific env (highest priority) */}}
  {{- range $envMap := $appEnv }}
    {{- $readerApplicationEnv = append $readerApplicationEnv $envMap }}
    {{- $_ := set $allNames $envMap.name true }}
  {{- end }}
  
  {{/* Then add template env if not already added */}}
  {{- range $envMap := $templateEnv }}
    {{- if not (hasKey $allNames $envMap.name) }}
      {{- $readerApplicationEnv = append $readerApplicationEnv $envMap }}
      {{- $_ := set $allNames $envMap.name true }}
    {{- end }}
  {{- end }}
  
  {{/* Finally add required reader env if not already added */}}
  {{- range $envMap := $readerEnv }}
    {{- if not (hasKey $allNames $envMap.name) }}
      {{- $readerApplicationEnv = append $readerApplicationEnv $envMap }}
      {{- $_ := set $allNames $envMap.name true }}
    {{- end }}
  {{- end }}

  {{/* Create combined env list with overrides for manager */}}
  {{- $allNamesManager := dict }}
  {{- $managerApplicationEnv := list }}
  
  {{/* First add app-specific env (highest priority) */}}
  {{- range $envMap := $appEnv }}
    {{- $managerApplicationEnv = append $managerApplicationEnv $envMap }}
    {{- $_ := set $allNamesManager $envMap.name true }}
  {{- end }}
  
  {{/* Then add template env if not already added */}}
  {{- range $envMap := $templateEnv }}
    {{- if not (hasKey $allNamesManager $envMap.name) }}
      {{- $managerApplicationEnv = append $managerApplicationEnv $envMap }}
      {{- $_ := set $allNamesManager $envMap.name true }}
    {{- end }}
  {{- end }}
  
  {{/* Finally add required manager env if not already added */}}
  {{- range $envMap := $managerEnv }}
    {{- if not (hasKey $allNamesManager $envMap.name) }}
      {{- $managerApplicationEnv = append $managerApplicationEnv $envMap }}
      {{- $_ := set $allNamesManager $envMap.name true }}
    {{- end }}
  {{- end }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "inference-stack.fullname" $ }}-{{ $appName }}-reader
  labels:
    app.kubernetes.io/component: application-{{ $appName }}
    {{- include "inference-stack.labels" $ | nindent 4 }}
data:
  config.yaml: |
    takeoff:
      server_config:
        internal_port: 3005
      readers_config:
        {{ $appName }}:
          {{- $finalReadersConfig := $mergedValues.readerConfig }}          
          {{- range $key, $value := $finalReadersConfig }}
          {{ snakecase $key }}: {{ $value }}
          {{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "inference-stack.fullname" $ }}-{{ $appName }}-manager
  labels:
    app.kubernetes.io/component: application-{{ $appName }}
    {{- include "inference-stack.labels" $ | nindent 4 }}
data:
  config.yaml: |
    takeoff:
      server_config:
        internal_port: 3005
      readers_config:
        {{ $appName }}-manager:
          {{- $readerConfigTemplate := printf `
          internalGatewayIp: %s-gateway
          ` (include "inference-stack.fullname" $) }}
          {{- $templateReaderConfig := fromYaml $readerConfigTemplate }}
          {{- $managerOverrides := dict }}
          {{- if $mergedValues.managerConfig.enabled }}
          {{- if hasKey $mergedValues.managerConfig "skipSglangReader" }}
          {{- $_ := set $managerOverrides "skipSglangReader" $mergedValues.managerConfig.skipSglangReader }}
          {{- end }}
          {{- if hasKey $mergedValues.managerConfig "sglangPort" }}
          {{- $_ := set $managerOverrides "sglangPort" $mergedValues.managerConfig.sglangPort }}
          {{- end }}
          {{- end }}
          {{- $finalManagerConfig := merge $mergedValues.readerConfig $templateReaderConfig $managerOverrides }}
          {{- range $key, $value := $finalManagerConfig }}
          {{ snakecase $key }}: {{ $value }}
          {{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "inference-stack.fullname" $ }}-{{ $appName }}
  labels:
    app.kubernetes.io/component: application-{{ $appName }}
    {{- include "inference-stack.labels" $ | nindent 4 }}
spec:
  {{- if not $mergedValues.scaling.enabled }}
  replicas: {{ $mergedValues.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/component: application-{{ $appName }}
      {{- include "inference-stack.selectorLabels" $ | nindent 6 }}
  template:
    metadata:
      {{- with $mergedValues.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app.kubernetes.io/component: application-{{ $appName }}
        {{- include "inference-stack.labels" $ | nindent 8 }}
        {{- with $mergedValues.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with $.Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "inference-stack.serviceAccountName" $ }}
      {{- with $mergedValues.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
        - name: models-cache-manager
          image: busybox
          command: ["sh", "-c", "chmod -R 777 /models"]
          volumeMounts:
          - mountPath: /models
            name: {{ $mergedValues.modelsVolume.name }}
      containers:
        - name: {{ include "inference-stack.fullname" $ }}-{{ $appName }}-reader
          {{- with $mergedValues.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ $mergedValues.image.repository }}:{{ $mergedValues.image.tag | default (print $.Chart.AppVersion "-gpu") }}"
          imagePullPolicy: {{ $mergedValues.image.pullPolicy }}
          env:
            {{ $readerApplicationEnv | toYaml | nindent 12 }}
          {{- with $mergedValues.ports }}
          ports:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $mergedValues.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $mergedValues.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $mergedValues.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: reader-config
              mountPath: /code/config.yaml
              subPath: config.yaml
            - name: dshm
              mountPath: /dev/shm
            - name: {{ $mergedValues.modelsVolume.name }}
              mountPath: /code/models
          {{- with $mergedValues.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
        
        {{- if $mergedValues.managerConfig.enabled }}
        - name: {{ include "inference-stack.fullname" $ }}-{{ $appName }}-manager
          {{- with $mergedValues.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ $mergedValues.image.repository }}:{{ $mergedValues.image.tag | default (print $.Chart.AppVersion "-gpu") }}"
          imagePullPolicy: {{ $mergedValues.image.pullPolicy }}
          env:
            {{ $managerApplicationEnv | toYaml | nindent 12 }}
          {{- with $mergedValues.ports }}
          ports:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $mergedValues.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $mergedValues.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $mergedValues.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: manager-config
              mountPath: /code/config.yaml
              subPath: config.yaml
            - name: dshm
              mountPath: /dev/shm
            - name: {{ $mergedValues.modelsVolume.name }}
              mountPath: /code/models
          {{- with $mergedValues.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
        {{- end }}
      volumes:
        - name: reader-config
          configMap:
            name: {{ include "inference-stack.fullname" $ }}-{{ $appName }}-reader
        - name: manager-config
          configMap:
            name: {{ include "inference-stack.fullname" $ }}-{{ $appName }}-manager
        - name: dshm
          emptyDir:
            medium: Memory
            {{- if $mergedValues.shmSize }}
            sizeLimit: {{ $mergedValues.shmSize }}
            {{- end }}
        - {{- $mergedValues.modelsVolume | toYaml | nindent 10 }}
      {{- with $mergedValues.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $mergedValues.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $mergedValues.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $mergedValues.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
{{- if $mergedValues.scaling.enabled }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ include "inference-stack.fullname" $ }}-{{ $appName }}
  labels:
    app.kubernetes.io/component: application-{{ $appName }}
    {{- include "inference-stack.labels" $ | nindent 4 }}
  {{- with $mergedValues.scaling.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- $scaledObjectTemplate := printf `
scaleTargetRef:
  apiVersion: apps/v1
  kind: Deployment
  name: %s-%s
` (include "inference-stack.fullname" $) $appName }}
{{- $templateScalingSpec := fromYaml $scaledObjectTemplate }}

{{- $consumerGroupKey := printf "target_%s" $mergedValues.readerConfig.consumerGroup }}
{{- $serviceName := printf "%s-%s" (include "inference-stack.fullname" $) $appName }}
{{- $scalerAddress := printf "%s-gateway.%s.svc.cluster.local:3005" (include "inference-stack.fullname" $) $.Release.Namespace}}
{{- $target := (toString $mergedValues.scaling.metricTarget.value)}}

{{- $triggers := list }}
  {{- $trigger := dict "type" "external-push" "metadata" (dict "scalerAddress" $scalerAddress $consumerGroupKey $target) }}
  {{- $triggers = append $triggers $trigger }}

{{- $specWithoutMetricTarget := omit $mergedValues.scaling.spec "metricTarget" }}
{{- $specWithTriggers := merge $specWithoutMetricTarget (dict "triggers" $triggers) }}
{{- $finalScalingSpec := merge $specWithTriggers $templateScalingSpec }}

spec:
  {{- toYaml $finalScalingSpec | nindent 2 }}
---
{{- end }}
{{- end }}
# End range over applications
