kube-prometheus-stack:
  prometheus:
    serviceMonitor:
      scrapeInterval: 15s

    prometheusSpec:
      retention: 1y

      storageSpec:
        volumeClaimTemplate:
          metadata:
            name: prom
          spec:
            storageClassName: ""
            accessModes: [ "ReadWriteOnce" ]
            resources:
              requests:
                storage: 100Gi

  alertmanager:
    # Example configuration for Alertmanager
    enabled: trued

  defaultRules:
    create: false

  grafana:
    enabled: true

    grafana.ini:
      unified_alerting:
        enabled: true

      security:
        allow_embedding: true

    sidecar: #todo don't need a sidecar here
      dashboards:
        enabled: true
        label: grafana_dashboard # kube-prometheus-stack mandates it be labelled this
