{{- range $map_name, $payload := .Values.configMaps }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $map_name }}
  labels:
    app.kubernetes.io/component: rag
    {{- include "rag.labels" $ | nindent 4 }}
{{ toYaml $payload }}
---
{{- end}}
{{- if .Values.exportFeedback}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-mongodb-feedback-exporter
data:
  export_feedback.py: |
{{ .Files.Get "export_feedback.py" | indent 4 }}
---
{{- end }}
{{- if .Values.dpp.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: takeoff-pro-config
  labels:
    app: takeoff-pro
data:
  config.yaml: |
    takeoff:
      server_config:
        internal_port: 3005
      readers_config:
        document_processor:
          model_name: TitanML/document_processor
          device: cpu
          consumer_group: primary
{{- end }}