apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rag.fullname" $ }}-server
  labels:
    {{- include "rag.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ include "rag.fullname" $ }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "rag.selectorLabels" $ | nindent 6 }}
      app.kubernetes.io/component: {{ include "rag.fullname" $ }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: {{ include "rag.fullname" $ }}
        {{- include "rag.labels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: server
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- include "rag.BackendEnv" . | nindent 12 }}
          {{- with .Values.ports }}
          ports:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
          - name: server-data
            mountPath: /tmp/data_store
          {{- with .Values.volumeMounts }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
        
        {{- if .Values.exportFeedback }}
        - name: feedback-exporter
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["python", "export_feedback.py"]
          env:
            {{- include "rag.BackendEnv" . | nindent 12 }}
          volumeMounts:
            - name: postgres-mongodb-feedback-exporter
              mountPath: /TakeoffRag/helios/export_feedback.py
              subPath: export_feedback.py
        {{- end }}
      volumes:
      {{- if .Values.exportFeedback }}
      - name: postgres-mongodb-feedback-exporter
        configMap:
          name: postgres-mongodb-feedback-exporter
      {{- end }}
      - name: server-data
        {{- if not .Values.dataCache.enabled }}
        emptyDir: {}
        {{- else }}
        persistentVolumeClaim:
          claimName: {{ .Values.dataCache.persistentVolumeClaim }}
        {{- end }}
      {{- with .Values.volumes }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
{{- if .Values.dpp.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.dpp.name }}
  labels:
    app: {{ .Values.dpp.name }}

spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.dpp.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.dpp.name }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: takeoff-pro
          image:  "{{ .Values.dpp.image.repository }}:{{ .Values.dpp.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.dpp.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          {{- with .Values.dpp.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.dpp.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.dpp.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.dpp.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: config-volume
              mountPath: /code/config.yaml
              subPath: config.yaml
              readOnly: true
      volumes:
        - name: config-volume
          configMap:
            name: {{ .Values.dpp.name }}
{{- end }}