{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "rag.fullname" $ }}
  labels:
    app.kubernetes.io/component: {{ include "rag.fullname" $ }}
    {{- include "rag.labels" $ | nindent 4 }}
spec:
  endpoints:
  - interval: 15s
    targetPort: 8000
    path: /metrics
  selector:
    matchLabels:
      app.kubernetes.io/component: {{ include "rag.fullname" $ }}
---
{{- end }}