apiVersion: v1
kind: Service
metadata:
  name: {{ include "rag.fullname" $ }}
  labels:
    app.kubernetes.io/component: server
    {{- include "rag.labels" $ | nindent 4 }}
  {{- with .Values.server.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ports:
    {{- range $port := .Values.server.ports }}
    - port: {{ $port.containerPort }}
      targetPort: http
      protocol: {{ $port.protocol }}
      name: {{ $port.name }}
    {{- end }}
  selector:
    app.kubernetes.io/component: server
    {{- include "rag.selectorLabels" $ | nindent 4 }}
---
{{- if .Values.enableAWSLoadBalancer }}
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "external"
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
    helm.sh/resource-policy: keep
  name: takeoff-server-lb
spec:
  type: LoadBalancer
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: api
  selector:
    app.kubernetes.io/component: server
---
{{- end }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "rag.fullname" $ }}-postgres
  labels:
    app.kubernetes.io/component: postgres
    {{- include "rag.labels" $ | nindent 4 }}
spec:
  ports:
  - port: 5432
  selector:
    app.kubernetes.io/component: postgres