name: Inference Stack Helm Chart Tests

on:
  push:
    branches: [main]
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

jobs:
  helm-unittest-inference-stack:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: "latest"

      - name: Run Helm lint for rag
        working-directory: ./charts/rag
        run: |
          helm lint .

      - name: Run Helm lint for console
        working-directory: ./charts/console
        run: |
          helm lint .

      - name: Run Helm lint for onwards
        working-directory: ./charts/onwards
        run: |
          helm lint .

      - name: Run Helm lint for observability
        working-directory: ./charts/observability
        run: |
          helm lint .
