name: Model Orchestra Helm Chart Tests

on:
  push:
    branches: [main]
    paths:
      - "charts/model-orchestra/**"
  pull_request:
    branches: [main]
    paths:
      - "charts/model-orchestra/**"

jobs:
  helm-unittest-model-orchestra:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: "latest"

      - name: Install Helm unittest plugin
        run: |
          helm plugin install https://github.com/helm-unittest/helm-unittest

      - name: Run Helm lint
        working-directory: ./charts/model-orchestra
        run: |
          helm lint .
      
      - name: Run Helm lint
        working-directory: ./charts/monitoring
        run: |
          helm lint .

      - name: Run Helm lint
        working-directory: ./charts/console
        run: |
          helm lint .

      - name: Run Helm unittest
        working-directory: ./charts/model-orchestra
        run: |
          helm unittest .
