---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "takeoff.fullname" $ }}-controller
  labels:
    app.kubernetes.io/component: controller
    {{- include "takeoff.labels" $ | nindent 4 }}
data:
  config.yaml: |
    takeoff:
      server_config:
        internal_port: 3005
        {{- range $key, $value := .Values.controller.config }}
        {{ snakecase $key}}: {{$value}}
        {{- end }}
      readers_config:
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "takeoff.fullname" . }}-controller
  labels:
    app.kubernetes.io/component: controller
    {{- include "takeoff.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.controller.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/component: controller
      {{- include "takeoff.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.controller.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app.kubernetes.io/component: controller
        {{- include "takeoff.labels" . | nindent 8 }}
        {{- with .Values.controller.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "takeoff.serviceAccountName" . }}
      {{- with .Values.controller.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}-controller
          {{- with .Values.controller.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.controller.image.repository }}:{{ .Values.controller.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.controller.image.pullPolicy }}
          env:
            {{- include "takeoff.controllerEnv" . | nindent 12 }}
          {{- with .Values.controller.ports }}
          ports:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.controller.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.controller.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.controller.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: config
              mountPath: /code/config.yaml
              subPath: config.yaml
          {{- with .Values.controller.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ include "takeoff.fullname" $ }}-controller
      {{- with .Values.controller.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.controller.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.controller.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.controller.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "takeoff.fullname" . }}-controller
  labels:
    app.kubernetes.io/component: controller
    {{- include "takeoff.labels" . | nindent 4 }}
spec:
  type: {{ .Values.controller.service.type }}
  {{- with .Values.controller.service.ports }}
  ports:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    app.kubernetes.io/component: controller
    {{- include "takeoff.selectorLabels" . | nindent 4 }}
---
{{- if .Values.controller.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "takeoff.fullname" . }}-controller
  labels:
    app.kubernetes.io/component: controller
    {{- include "takeoff.labels" . | nindent 4 }}
  {{- with .Values.controller.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.controller.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  {{- if .Values.controller.ingress.tls }}
  tls:
    {{- range .Values.controller.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.controller.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            {{- with .pathType }}
            pathType: {{ . }}
            {{- end }}
            backend:
              service:
                name: {{ include "takeoff.fullname" . }}-controller
                port:
                  number: {{ .Values.controller.service.port }}
          {{- end }}
    {{- end }}
{{- end }}
---
{{- if .Values.controller.exportPrometheusMetrics }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "takeoff.fullname" $ }}-controller
spec:
  endpoints:
  - interval: 15s
    targetPort: 3001
    path: /metrics
  selector:
    matchLabels:
      app.kubernetes.io/component: controller
---
{{- end }}